import org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension
import org.jetbrains.kotlin.gradle.plugin.KotlinMultiplatformPluginWrapper
import org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask

/**
 * Extension to configure the ResourceIndex generation task
 */
interface ResourceIndexExtension {
    val resourcesDirectory: DirectoryProperty
    val outputDirectory: DirectoryProperty
    val packageName: Property<String>
}

/**
 * Task to generate ResourceIndex.kt with all markdown files organized by category
 */
abstract class GenerateResourceIndexTask : DefaultTask() {

    @get:InputDirectory
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val resourcesDir: DirectoryProperty

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @get:Input
    abstract val packageName: Property<String>

    @TaskAction
    fun generate() {
        val inputDir = resourcesDir.get().asFile
        val output = outputFile.get().asFile

        // Scan subdirectories in resources directory
        val categories = mutableMapOf<String, MutableList<String>>()

        inputDir.listFiles()?.filter { it.isDirectory }?.forEach { categoryDir ->
            val categoryName = categoryDir.name
            val mdFiles = categoryDir.listFiles()
                ?.filter { it.extension == "md" }
                ?.map { it.name }
                ?.sorted()
                ?: emptyList()

            if (mdFiles.isNotEmpty()) {
                categories[categoryName] = mdFiles.toMutableList()
            }
        }

        // Generate Kotlin code
        val code = buildString {
            appendLine("package ${packageName.get()}")
            appendLine()
            appendLine("/**")
            appendLine(" * Auto-generated file containing index of all question resources.")
            appendLine(" * DO NOT EDIT MANUALLY - Generated by generateResourcesIndex task")
            appendLine(" */")
            appendLine()
            appendLine("data class CategoryInfo(")
            appendLine("    val path: String,")
            appendLine("    val files: List<String>")
            appendLine(")")
            appendLine()
            appendLine("object ResourceIndex {")
            appendLine("    val categories: Map<String, CategoryInfo> = mapOf(")

            categories.entries.forEachIndexed { index, (categoryName, files) ->
                appendLine("        \"$categoryName\" to CategoryInfo(")
                appendLine("            path = \"files/$categoryName\",")
                append("            files = listOf(\n")
                files.forEachIndexed { fileIndex, fileName ->
                    append("                \"$fileName\"")
                    if (fileIndex < files.size - 1) append(",\n")
                }
                appendLine()
                appendLine("            )")
                append("        )")
                if (index < categories.size - 1) appendLine(",")
                else appendLine()
            }

            appendLine("    )")
            appendLine("}")
        }

        // Write generated code
        output.parentFile.mkdirs()
        output.writeText(code)

        logger.lifecycle("Generated ResourceIndex.kt with ${categories.size} categories:")
        categories.forEach { (name, files) ->
            logger.lifecycle("  - $name: ${files.size} files")
        }
    }
}

// Configure the extension
val extension = extensions.create<ResourceIndexExtension>("resourceIndex")

// Set default values
extension.resourcesDirectory.convention(
    project.layout.projectDirectory.dir("src/commonMain/composeResources/files")
)
extension.outputDirectory.convention(
    project.layout.buildDirectory.dir("generated/questionsIndex")
)
extension.packageName.convention("de.felixlf.questionsapp.data")


val generateResourcesIndex = tasks.register<GenerateResourceIndexTask>("generateResourcesIndex") {
    group = "build"
    description = "Generates ResourceIndex.kt with all markdown files organized by category"

    resourcesDir.set(extension.resourcesDirectory)
    packageName.set(extension.packageName)

    // Output file is package path + ResourceIndex.kt
    outputFile.set(
        extension.outputDirectory.map { dir ->
            val packagePath = extension.packageName.get().replace('.', '/')
            dir.file("$packagePath/ResourceIndex.kt")
        }
    )
}

tasks.withType<KotlinCompilationTask<*>>().configureEach {
    dependsOn(generateResourcesIndex)
}

plugins.withType<KotlinMultiplatformPluginWrapper> {
    extensions.configure<KotlinMultiplatformExtension> {
        sourceSets.named("commonMain") {
            kotlin.srcDir(extension.outputDirectory)
        }
    }
}
